apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - image: arunvelsriram/utils
      name: debug-pod
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
